import Companies from '@/components/Companies';
import Details from '@/components/Details';
import Footer from '@/components/Footer';
import CallToAction from '@/components/CallToAction';
import Guide from '@/components/Guide';
import Hero from '@/components/Hero';
import Properties from '@/components/Properties';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Companies />
      <Guide />
      <Properties />
      <Details />
      <CallToAction />
      <Footer />
    </>
  );
}
